### ISSUE TITLE
Stale registry image and general project status

### ISSUE THREAD

**Issue by gnattishness** [helderco/docker-gen#4]
Hi,
I noticed the dockerhub registry entry is now pretty stale, missing the subsequent upstream releases at `nginxproxy/docker-gen`.

From what I see, the current Dockerfile would only need to change the base image to `nginxproxy/docker-gen` (the upstream project has since been transferred)

Is this project still usable/used, or would you recommend against it?

If it shouldn't be used, do you have any alternative solution you know of?

Thanks!!

**Comment by helderco** [comment]
Hi, unfortunately I haven't used this for a while. I've adopted Traefik instead. But I can update the image if it's still useful.

**Comment by helderco** [comment]
Docker hub no longer has automated builds for free, so you can get latest image from Github: https://github.com/helderco/docker-gen/pkgs/container/docker-gen

**Comment by gnattishness** [comment]
Thanks! Much appreciated.
Now that docker-gen is more actively supported, I'll see about integrating the functionality directly in the medium future.
